508 implement file store backend
DataMigration-International-AG/jivs-docstore pull request #6
Opened 2024-06-10 09:41 UTC by hdg4jivs

## Describe your changes briefly

## Issue ticket number with link
closes  /DataMigration-International-AG/jivs-occ#508
## Database changes
- Add schema jds
- Add table JIVS-DOCSTORE
- Add table JIVS-DOCUMENT-PARAM
- 
## Pre-Review checklist
- [x] I reviewed my code
- [x] The code is runnable
- [ ] I tested the code with edge cases
- [x] I wrote tests for my code

Please review. Thank you.

2024-06-10 09:50 UTC, hdg4jivs commented
@mhn4jivs @Involute1 
The way I wrote the code for the service component is that it returns an Optional<SOMETHING> and not the SOMETHING. 
The controller is then checking if the Optional<> isPresent() and decides if it should return the actual value or null / empty List.

Should the Service check if the Optional is present and do above mentioned logic?

2024-06-10 10:01 UTC, Involute1 commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +				documentDTOList.add(documentDTOWithParams);
nitpick: you already give it an Optional of List<DocumentDTO> why do you parse it again?

2024-06-10 10:02 UTC, Involute1 commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +		Optional<Map<String, String>> result = documentService.getParams(documentDTO.id());
nitpick: i dont like the name of the method. Also why are we parsing this again you already have a documentdto?

2024-06-10 10:04 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/DatabaseManager.java
> +				logger.debug("Connected to {}", result.getMetaData().getURL());
nitpick: use jivs config for this

2024-06-10 10:05 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/IDao.java
> +	Optional<List<T>> getAllAsList() throws JPEPersistenceException;
nitpick: in my opinon we dont need the optinal here, on error we return an empty list

2024-06-10 10:05 UTC, mhn4jivs commented
> @mhn4jivs @Involute1 The way I wrote the code for the service component is that it returns an Optional< SOMETHING > and not the SOMETHING. The controller is then checking if the Optional<> isPresent() and decides if it should return the actual value or null / empty List.
> 
> Should the Service check if the Optional is present and do above mentioned logic?



> @mhn4jivs @Involute1 The way I wrote the code for the service component is that it returns an Optional< SOMETHING > and not the SOMETHING. The controller is then checking if the Optional<> isPresent() and decides if it should return the actual value or null / empty List.
> 
> Should the Service check if the Optional is present and do above mentioned logic?

Imo the Controller will decide what to do.

2024-06-10 10:05 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/db/DbDao.java
> +		} catch (SQLException | JPEPersistenceException e) {
nitpick: where logging?

2024-06-10 10:06 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/IDao.java
> +	void update(T t) throws JPEPersistenceException;
nitpick: should also return updated object

2024-06-10 10:07 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +
issue: why is this empty?

2024-06-10 10:08 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/docstore/IDocumentDao.java
> +public interface IDocumentDao extends IDao<DocumentDTO, UUID> {
issue: dao should always return the entity not the dto

2024-06-10 10:09 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/param/DocumentParamDao.java
> +		return Optional.empty();
nitpick: why not implemented? if we dont need it throw an error pls

2024-06-10 10:09 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/param/DocumentParamDao.java
> +		return Optional.empty();
nitpick: why not implemented? if we dont need it throw an error pls

2024-06-10 10:10 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/param/DocumentParamDao.java
> +
nitpick: why not implemented? if we dont need it throw an error pls

2024-06-10 10:10 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/param/IDocumentParamDao.java
> +	void updateParams(UUID id, Map<String, String> params) throws JPEPersistenceException;
nitpick: should also return the updated Map as optional

2024-06-10 10:12 UTC, Involute1 commented on src/main/java/com/datamigration/jds/service/DocumentService.java
> +		return DTOUtil.toDocumentDTO(document);
nitpick: why not return insertedDocumentDto ?

2024-06-10 10:13 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/DatabaseConfig.java
issue: this wont be need when you use jivs-config

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/ErrorCode.java
> +	WATCHER_CONFIG_ERROR("JPE-703", "Error regarding the libraries watcher configuration"),
issue: the JPE is not correct since we are not in the process engine

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/checked/JPEException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/checked/JPENotImplementedException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/checked/JPEPersistenceException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/checked/JPESystemException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/unchecked/JPEUncheckedConfigurationException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:14 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/unchecked/JPEUncheckedException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:15 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/unchecked/JPEUncheckedNotImplementedException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:15 UTC, Involute1 commented on src/main/java/com/datamigration/jds/util/exceptions/unchecked/JPEUncheckedPersistenceException.java
issue: class Name should use the correct abbreviation

2024-06-10 10:25 UTC, hdg4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +
Because as of task definition we only update the params

2024-06-10 10:35 UTC, mhn4jivs requested changes

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/model/docstore/JivsDocument.java
> +	public JivsDocument(byte[] fileBin, String filename, String documentType, UUID creatorId, UUID customerId, UUID systemId,
Question: Why do we have these two constructors? It does not make sense to me. I would make the deleted a default on DB side and not use it here

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +		} catch (SQLException e) {
nitpick: logging

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +		} catch (Exception e) {
nitpick: logging in whole class

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +	public boolean updateDeleteFlag(UUID id) throws JPEPersistenceException {
nitpick: naming? update to what?

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/IDocumentSQLs.java
praise: nice escaping

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/param/DocumentParamDao.java
nitpick: logging

2024-06-10 10:35 UTC, mhn4jivs commented on src/main/resources/config.properties
question: is this placed correctly?

2024-06-10 10:41 UTC, hdg4jivs commented on src/main/java/com/datamigration/jds/model/docstore/JivsDocument.java
> +	public JivsDocument(byte[] fileBin, String filename, String documentType, UUID creatorId, UUID customerId, UUID systemId,
Make sense, I wrote it because of the easier usage in test. Removing one constructor and the deleted param. 
Setting the deleted column to false on insert.

2024-06-10 10:58 UTC, hdg4jivs commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +		Optional<Map<String, String>> result = documentService.getParams(documentDTO.id());
Might be an unfortunate name of the parameter, I'm checking if the Optional<List<DocumentDTO>> contains a list or if it's null, I believe

2024-06-10 11:13 UTC, hdg4jivs commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +		Optional<Map<String, String>> result = documentService.getParams(documentDTO.id());
Actually you are right. In those getList methods in the dao, the Optional.of(new ArrayList()) is always assigned to the return value if there're no errors.

2024-06-11 05:59 UTC, mhn4jivs requested changes

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +	public Map<String, String> updateParams(UUID id, Map<String, String> params) throws JDSPersistenceException {
question: not sure what the decision was @Involute1 but did we not say that updates are void?

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +	public List<JivsDocument> getByDocumentType(String documentType) throws JDSPersistenceException {
nitpick: if we get a list maybe we should describe it in the method name. I think there is a convention that we add "asList" to the method name.

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/DatabaseManager.java
> +		} catch (SQLException e) {
nitpick: inconsistent exception handling here. also logging is weird. plus ou dont want to printout the password

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/db/DbDao.java
> +		} catch (SQLException | JDSPersistenceException e) {
question: y u no log

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +				if (rs.next()) {
nitpick: since you are catching the same exception, could you maybe merge the catches to the outer catch? Also if you use insert you could split it up into something like that as a general idea, you can discuss with @Involute1 :
```

int insertedRows = preparedStatement.executeUpdate();
if (insertedRows == 0) {
    logger.error("Document insertion failed.");
    throw new JDSPersistenceException(ErrorCode.DB_NO_RESULT_ERROR);
}

try (ResultSet rs = preparedStatement.getGeneratedKeys()) {
    if (rs.next()) {
        UUID id = UUID.fromString(rs.getString(1));
        document.setId(id);
        result = document;
    } else {
        logger.error("Document could not be inserted, no ID generated.");
        throw new JDSPersistenceException(ErrorCode.DB_NO_RESULT_ERROR);
    }
}
```

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +				throw new JDSPersistenceException(e, ErrorCode.DB_READ_ERROR);
nitpick: exception merging maybe too

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +			} catch (SQLException e) {
nitpick: exception merging maybe too

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/IDocumentDao.java
nitpick: same thing with the naming "asList" i mentioned before

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/persistence/param/DocumentParamDao.java
> +						resultMap.put(entry.getKey(), entry.getValue());
nitpick: exception merging maybe too

2024-06-11 05:59 UTC, mhn4jivs commented on src/main/java/com/datamigration/jds/service/DocumentService.java
nitpick: naming with asList

2024-06-11 07:19 UTC, Involute1 commented on src/main/java/com/datamigration/jds/controller/DocStoreManager.java
> +	public Map<String, String> updateParams(UUID id, Map<String, String> params) throws JDSPersistenceException {
yes this is true but i forgot to tell @hdg4jivs

2024-06-11 07:29 UTC, Involute1 commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +				if (rs.next()) {
generally @mhn4jivs approach is a bit cleaner, but i am fine with both. But in any case i would try to merge the catch blocks since you are catching the same thing over and over again

2024-06-13 13:08 UTC, hdg4jivs commented on src/main/java/com/datamigration/jds/persistence/docstore/DocumentDao.java
> +				if (rs.next()) {
Not possible without an actual identity, which has to be of a numeric type, column.

2024-06-13 14:29 UTC, merged